### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by mgrapiniak** [brucesdad13/AlienWhoopF0#1]
Hi :)

Resource folder is mentioned in README however there istn’t any.
Cheers!

**Comment by nikdavis** [comment]
For what it's worth, I created a BOM here for my build:
https://docs.google.com/spreadsheets/d/191TaZBGoiIGVvG6H7Qhd4fEgC2I_8c7Ob6JJ-dZdGsY/edit?usp=sharing

@brucesdad13 Feel free to use it as you see fit. I can PR the readme if you like. I created it using Eagle and wrapped up multiple parts into single rows. I also added a note about possible MPU-6500 compatibility in the dearth of MPU-6881s, given notes in the discord and at minimum verifying pin compatibility. 

Edit: I just opened a PR if you find it useful, #2

**Comment by brucesdad13** [comment]
Thanks! I'll update the README etc. I actually have some other changes to
push out like sharper corners ...
